### ISSUE TITLE
Add Bintray credentials to .travis.yml

### ISSUE THREAD

**Issue by BenFradet** [snowplow-referer-parser/scala-referer-parser#26]
- BINTRAY_SNOWPLOW_MAVEN_USER
- BINTRAY_SNOWPLOW_MAVEN_API_KEY

---
- [x] AD: add creds
- [x] AD: create repo in Bintray
- [x] BF: push first M1
- [x] BF: add to JCenter
- [x] AD: activate Maven Central sync

**Comment by alexanderdean** [comment]
There's a dodgy commit to fixup.

**Comment by alexanderdean** [comment]
Repo created, https://bintray.com/snowplow/snowplow-maven/scala-referer-parser

I've renamed this repo too given we are getting rid of Java.

**Comment by alexanderdean** [comment]
@ me when you are ready for the remaining steps.
