### ISSUE TITLE
Replace test referers database by a mock

### ISSUE THREAD

**Issue by ispringer** [snowplow-referer-parser/scala-referer-parser#36]
This project has an ASL 2.0 license, which is great. However, one of its key components - referers.yml/json appears to be licensed under GPL 3.0. From https://github.com/snowplow-referer-parser/referer-parser:

> referers.yml is based on Piwik's SearchEngines.php and Socials.php, copyright 2012 Matthieu Aubry and available under the GNU General Public License v3.

Don't these two licenses conflict?

**Comment by alexanderdean** [comment]
As of 4c25ed2cc00f69e643569437934db1e8ebb8ad4e (which will be in the next release), the referers database is no longer contained in the build artifacts - you bring in your own copy at runtime; you can opt to use an alternative to the GPL 3.0-ed data file should you so wish.

For the prevention of any confusion, it's probably worth switching out the referers.yml/json that is included in this repo for *test purposes* with a minimal homegrown mock that is ASL 2.0 licensed.

Assigning to @BenFradet to consider.

**Comment by BenFradet** [comment]
Thanks for the heads up @ispringer :+1:

**Comment by ispringer** [comment]
Good news...

Matomo (formerly Piwik) has moved the referrer definitions to a separate project:

https://github.com/matomo-org/searchengine-and-social-list

and according to the package.json and composer.json files in that project, they are licensed under CCO 1.0, which essentially means public domain!

What do you think of writing a script to convert the Matomo definition files over to the referers.json format and then either using that or using it as a starting point?

**Comment by alexanderdean** [comment]
Hey @ispringer - you can raise that suggestion in the data file project, happy to respond there - it doesn't impact on this (or any other) individual client library. The data file project is here:

https://github.com/snowplow-referer-parser/referer-parser
