### ISSUE TITLE
Do not double decode query string

### ISSUE THREAD

**Issue by pcode93** [snowplow-referer-parser/scala-referer-parser#73]
**Library version**: 0.5.0

**Expected behavior**: Parser should return `SearchReferer` for url `https://www.google.com/search?q=keyword+1%25+keyword`

**Actual behavior**: Parser throws `java.lang.IllegalArgumentException`

**Steps to reproduce**:
- Create a parser
- Run `parser.parse("https://www.google.com/search?q=keyword+1%25+keyword")`
- Parser throws `java.lang.IllegalArgumentException: URLDecoder: Illegal hex characters in escape (%) pattern - For input string: "+k"`

I believe this happens because the query string gets decoded twice.

First in `Parser.parse` on line `85` query string is extracted with `val query  = Option(refererUri.getQuery)`, with returns `q=keyword+1%+keyword`. `URI.getQuery` already decodes the query.

Then in `Parser.extractQueryParams` parts of the query are again decoded using `URLDecoder.decode`.

**Comment by BenFradet** [comment]
hey, could you try with 0.6.0-M2 which is being developed in #70

**Comment by pcode93** [comment]
tried with `"com.snowplowanalytics" %% "scala-referer-parser" % "0.6.0-M2"`, same thing

**Comment by BenFradet** [comment]
Thanks, scheduling for 0.6.0

**Comment by BenFradet** [comment]
I incorporated a fix in #70 , 0.6.0-M3 will be published momentarily :+1:
