### ISSUE TITLE
Update referer.yml

### ISSUE THREAD

**Issue by lukeindykiewicz** [snowplow-referer-parser/scala-referer-parser#75]
Update `referer.yml` file in scala-referer-parser 0.3.0.
Backport to version 0.3.0 possibility to read latest referrers from https://s3-eu-west-1.amazonaws.com/snowplow-hosted-assets/third-party/referer-parser/referers-latest.yml

**Comment by chuwy** [comment]
I'm just not sure the ticket name makes sense. I think `0.3.0` here is irrelevant? It can be just `Update referers.yml`. We usually try to use same ticket names for recurring tasks, but previous update was too long time ago when we didn't have any conventions.

**Comment by lukeindykiewicz** [comment]
Ok, I'll rename it.
